DEBUG:root:Order:2 17 4.0
DEBUG:root:Finish turn

ERROR:root:Error in bot.
Traceback (most recent call last):
  File "opponent_bots/aggressive_bot.py", line 75, in <module>
    current_line = input()
EOFError: EOF when reading a line
